# Generated by Django 5.0.4 on 2024-04-07 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('connectionKey', models.CharField(max_length=48)),
                ('password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('serverClients', models.ManyToManyField(related_name='serverClients', to='server_listings_app.user')),
                ('serverHost', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_listings_app.user')),
            ],
        ),
    ]
