# Generated by Django 5.0.4 on 2024-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_listings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='connectionKey',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
