# Generated by Django 5.0.4 on 2024-04-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_listings_app', '0002_alter_server_connectionkey_alter_server_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='serverClients',
            field=models.ManyToManyField(blank=True, null=True, related_name='serverClients', to='server_listings_app.user'),
        ),
    ]
