# Generated by Django 5.0.4 on 2024-04-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_listings_app', '0003_alter_server_serverclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='dateEnded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='dateStarted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
