# Generated by Django 5.0.4 on 2024-04-08 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_listings_app', '0004_server_dateended_server_datestarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentServer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_listings_app.server'),
        ),
    ]
