# Generated by Django 5.0.4 on 2024-04-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_listings_app', '0005_user_currentserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numberOfServersHosted',
            field=models.IntegerField(db_default=0),
        ),
    ]
