name: Django CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        source ./djvenv/Scripts/activate
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        source ./djvenv/Scripts/activate
        python manage.py test
