name: Django CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Install Dependencies
      run: |
        source ./djvenv/Scripts/activate
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        source ./djvenv/Scripts/activate
        python manage.py test
